safe: true
lsi: false
pygments: true
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data
    - strikethrough

exclude:
  - 'README.md'
  - 'Gemfile'
  - 'CNAME'

# We can only have two levels of menu, this **** is hardcoded into the menu in
# the template. Entries have the following properties:
#  * `name`, link display name,
#  * `url`, URL for the page relative to root, must equal `page.url`,
#  * `href`, optional overrides `url`, used when linking to an `index.html` page
#    and  you don't want the URL to feature `index.html`. But `url` property
#   still needs to match `page.url` to set active tags correctly.
sections:
  - name: Introduction
    url:  /index.html
    href: /
    links:
      - name: Github Projects
        url:  https://github.com/taskcluster
  - name: Queue
    url:  /queue/index.html
    href: /queue/
    links:
    - name: Worker Interaction
      url:  /queue/worker-interaction/index.html
      href: /queue/worker-interaction/
    - name: API Documentation
      url:  /queue/api-docs/index.html
      href: /queue/api-docs/
    - name: AMQP Exchanges
      url:  /queue/exchanges/index.html
      href: /queue/exchanges/
    - name: Queue Web Interface
      url:  http://queue.taskcluster.net
    - name: Source Repository
      url:  https://github.com/taskcluster/taskcluster-queue
  - name: Scheduler
    url:  /scheduler/index.html
    href: /scheduler/
    links:
    - name: API Documentation
      url:  /scheduler/api-docs/index.html
      href: /scheduler/api-docs/
    - name: AMQP Exchanges
      url:  /scheduler/events/index.html
      href: /scheduler/events/
    - name: Source Repository
      url:  https://github.com/taskcluster/task-graph-scheduler
  - name: Services
    url:  /services/index.html
    href: /services/
    links:
      - name: AWS Provisioner (legacy)
        url:  /services/aws-provisioner/index.html
        href: /services/aws-provisioner/
      - name: Task Indexing
        url:  /services/index/index.html
        href: /services/index/
      - name: Purge Cache
        url:  /services/purge-cache/index.html
        href: /services/purge-cache/
  - name: Auth
    url:  /auth/index.html
    href: /auth/
    links:
      - name: Restricting Scopes
        url:  /auth/authorized-scopes/index.html
        href: /auth/authorized-scopes/
      - name: Temporary Credentials
        url:  /auth/temporary-credentials/index.html
        href: /auth/temporary-credentials/
      - name: Signed Urls
        url:  /auth/signed-urls/index.html
        href: /auth/signed-urls/
      - name: API Documentation
        url:  /auth/api-docs/index.html
        href: /auth/api-docs/
      - name: Authentication Manager
        url:  https://tools.taskcluster.net/auth/
      - name: Source Repository
        url:  https://github.com/taskcluster/taskcluster-auth
  - name: AWS Provisioner
    url:  /aws-provisioner/index.html
    href: /aws-provisioner/
    links:
    - name: API Documentation
      url:  /aws-provisioner/api-docs/index.html
      href: /aws-provisioner/api-docs/
    - name: AMQP Exchanges
      url:  /aws-provisioner/events/index.html
      href: /aws-provisioner/events/
    - name: Source Repository
      url:  https://github.com/taskcluster/aws-provisioner
  - name: Workers
    url:  /workers/index.html
    href: /workers/
    links:
      - name: Docker Worker
        url:  /workers/docker-worker/index.html
        href: /workers/docker-worker/
      - name: Generic Worker
        url:  /workers/generic-worker/index.html
        href: /workers/generic-worker/
  - name: Presentations
    url: /presentations/index.html
    href: /presentations/
    links:
      - name: TaskCluster Introduction
        url:  /presentations/intro/index.html
        href: /presentations/intro/
      - name: TaskCluster Scopes
        url:  /presentations/scopes/index.html
        href: /presentations/scopes/
  - name: Tools
    url:  /tools/index.html
    href: /tools/
    links:
      - name: Task Inspector
        url:  /tools/task-inspector/index.html
        href: /tools/task-inspector/
      - name: Task-Graph Inspector
        url:  /tools/task-graph-inspector/index.html
        href: /tools/task-graph-inspector/
      - name: Task Creator
        url:  /tools/task-creator/index.html
        href: /tools/task-creator/
      - name: Reference Formats
        url:  /tools/references/index.html
        href: /tools/references/
