safe: true
lsi: false
pygments: true
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data
    - strikethrough

exclude:
  - 'README.md'
  - 'Gemfile'
  - 'CNAME'
  - 'node_modules'

# We can only have two levels of menu, this **** is hardcoded into the menu in
# the template. Entries have the following properties:
#  * `name`, link display name,
#  * `url`, URL for the page relative to root, must equal `page.url`,
#  * `href`, optional overrides `url`, used when linking to an `index.html` page
#    and  you don't want the URL to feature `index.html`. But `url` property
#   still needs to match `page.url` to set active tags correctly.
sections:
  - name: About
    links:
    - name: Introduction
      url:  /index.html
      href: /
    - name: Getting Started
      url:  /introduction/getting-started/index.html
      href: /introduction/getting-started/
    - name: Blog
      url:  http://planet.mozilla.org/taskcluster
  - name: Learn
    links:
    - name: Introduction
      url:  /learn/index.html
      href: /learn/
    - name: Authenticate
      url:  /learn/authenticate/index.html
      href: /learn/authenticate
    - name: Create a Task
      url:  /learn/create-task/index.html
      href: /learn/create-task
    - divider: true
    - heading: Presentations
    - name: Screencasts
      url: /presentations/index.html
      href: /presentations/
    - name: TaskCluster Introduction
      url:  /presentations/intro/index.html
      href: /presentations/intro/
    - name: TaskCluster Scopes
      url:  /presentations/scopes/index.html
      href: /presentations/scopes/
      # name: Listening for Task Events (PulseListener + WebListener)
      # name: Tasks w. Custom Routes (custom routes, scopes, WebListener)
      # name: Browsing the Index
      # name: Indexing Tasks
      # name: Create a Task-Graph

      # name: Docker in docker-worker
      # name:
  - name: Tools
    links:
    - name: Web Tools
      url:  /tools/web/index.html
      href: /tools/web/
    - name: Client Libraries
      url:  /tools/clients/index.html
      href: /tools/clients/
    - name: Reference Formats
      url:  /tools/references/index.html
      href: /tools/references/
  - name: Platform
    links:
    - heading: Queue
    - name: Overview
      url:  /queue/index.html
      href: /queue/
    - name: Worker Interaction
      url:  /queue/worker-interaction/index.html
      href: /queue/worker-interaction/
    - name: API Documentation
      url:  /queue/api-docs/index.html
      href: /queue/api-docs/
    - name: AMQP Exchanges
      url:  /queue/exchanges/index.html
      href: /queue/exchanges/
    - divider: true
    - heading: Scheduler
    - name: Overview
      url:  /scheduler/index.html
      href: /scheduler/
    - name: API Documentation
      url:  /scheduler/api-docs/index.html
      href: /scheduler/api-docs/
    - name: AMQP Exchanges
      url:  /scheduler/events/index.html
      href: /scheduler/events/
    - divider: true
    - heading: Authentication
    - name: Overview
      url:  /auth/index.html
      href: /auth/
    - name: Restricting Scopes
      url:  /auth/authorized-scopes/index.html
      href: /auth/authorized-scopes/
    - name: Temporary Credentials
      url:  /auth/temporary-credentials/index.html
      href: /auth/temporary-credentials/
    - name: Signed Urls
      url:  /auth/signed-urls/index.html
      href: /auth/signed-urls/
    - name: API Documentation
      url:  /auth/api-docs/index.html
      href: /auth/api-docs/
  - name: Core Services
    links:
    - divider: true
    - heading: AWS Provisioner
    - name: Overview
      url:  /aws-provisioner/index.html
      href: /aws-provisioner/
    - name: API Documentation
      url:  /aws-provisioner/api-docs/index.html
      href: /aws-provisioner/api-docs/
    - name: AMQP Exchanges
      url:  /aws-provisioner/events/index.html
      href: /aws-provisioner/events/
    - divider: true
    - heading: Workers
    - name: Overview
      url:  /workers/index.html
      href: /workers/
    - name: Docker Worker
      url:  /workers/docker-worker/index.html
      href: /workers/docker-worker/
    - name: Generic Worker
      url:  /workers/generic-worker/index.html
      href: /workers/generic-worker/
    - divider: true
    - heading: Other Services
    - name: Index
      url:  /services/index/index.html
      href: /services/index/
    - name: Purge-Cache
      url:  /services/purge-cache/index.html
      href: /services/purge-cache/
    - name: GitHub
      url:  /services/taskcluster-github/index.html
      href: /services/taskcluster-github/
    - name: Secrets
      url:  /services/secrets/index.html
      href: /services/secrets/
    - name: Hooks
      url:  /services/hooks/index.html
      href: /services/hooks/
    - name: Cors-Proxy
      url: /services/cors-proxy/index.html
      href: /services/cors-proxy
  - name: Development
    links:
    - name: Github Projects
      url:  https://github.com/taskcluster
    - name: Conventions
      url:  /devel/conventions/index.html
      href: /devel/conventions/
    - name: Namespaces
      url:  /devel/namespaces/index.html
      href: /devel/namespaces/
